### ISSUE TITLE
深夜看到这个,给个star

### ISSUE THREAD

**Issue by SaucePlum** [LancherM/higurashi-killer#1]
咱就是说,能写个命令行的嘛

**Comment by LancherM** [comment]
谢谢。这个只是给群写的自娱自乐的小玩具，基于Mirai机器人框架，想使用的话只需要按照[Mirai](https://github.com/mamoe/mirai)的文档配置就可以了。
不太清楚命令行的意思，您是指做成Mirai插件的形式吗？
